### ISSUE TITLE
Campaign | Posters: X-button on Android not functional

### ISSUE THREAD

**Issue by JuliaFreitagBGSt** [verdigado/gruene-app#608]
### Describe the Bug

The X at the top left to cancel the editing of posters does not work, there is also no button to cancel, only "Eintrag löschen" or "Speichern". At least you can get away with saving without loss, but it is irritating.

![Image](https://github.com/user-attachments/assets/c5341594-7d89-4c55-bf93-82eb955e48ee)
![Image](https://github.com/user-attachments/assets/694c83cd-fcfe-41b2-8965-99c7fcbe30d8)

### Steps to Reproduce

1. Go to 'Posters'
2. Click on 'Edit'
3. Try to exit the view via 'X-Button'

### Expected Behavior

I expect an easy and intuitiv way of exiting the edit view in posters.

### Additional Information

The the system-related Android “back button” actually works, However, you don't need the X in the top left-hand corner, especially as it has no function but is misleading.

Note: when editing entries under doors or flyer, the X is also available. But there it works as cancel . Likewise in the smaller preview of Edit poster:
![Image](https://github.com/user-attachments/assets/00e70f2b-e64e-4441-8fe4-7df79a9df177)

**Comment by Stift** [comment]
I cannot reproduce this. The X is working on my device. I'm not sure what I should do here. 
The only thing I deduce from the screenshots that there may be some kind of "no-touch" area on the top as the device may not support the edge2edge (#499), but this is a wild guess as the device is very intrusive and shows some overlays on top of the app.

As a sidenote: Although the X may not be needed as on Android the BACK button is working the X is needed to have a consistent layout for iOS devices as well.

**Comment by JuliaFreitagBGSt** [comment]
@Stift Should I put you in touch with the user directly?

**Comment by Stift** [comment]
Maybe yes, but I don't have high hopes in finding a quick solution. I need to find a test device. :nerd_face:

**Comment by Meliphagidae** [comment]
Hello. 
Flipping the device to landscape (Querformat) makes the X actice. But there is no visible change, only the behavior changes 

![Image](https://github.com/user-attachments/assets/5f43b152-f658-4885-a16d-12bd66ad7620)

. Maybe your guess, that the bug is related to edge2edge (https://github.com/verdigado/gruene-app/issues/499) is right. 

How else could I help?
Greetings to Pankow 😄🌻

**Comment by JuliaFreitagBGSt** [comment]
After discussion this on a higher level we decided to put this issue from release 1 to the backlog. We agree, that probably #499  has something to do with it and verdigado needs to tackle this first. After solving #499 we are going to discuss optimizing mobile view.

**Comment by JuliaFreitagBGSt** [comment]
@Stift can you confirm that by solving #499 this issue is solved?

**Comment by Stift** [comment]
The change of #499 includes that we only show our widgets in a 'SafeArea'. Supposing that the device is giving that correctly to our app, I assume that this should be correct now. As you can read there are a lot of 'ifs' and as I was not able to reproduce it before and lack of a device to do so, I cannot finally confirm this with confidence. I suggest we ask @Meliphagidae after the release of #499.

**Comment by Stift** [comment]
@JuliaFreitagBGSt 
Last release: 26.02.2025
Merge of #499: 12.03.2025

The feature is not released yet!

**Comment by Meliphagidae** [comment]
> [@Meliphagidae](https://github.com/Meliphagidae) Can you confirm that this issue is solved? :)
No! 
After it will be released I can test otherwise I would need to know, how I can get the pre release for testing.

**Comment by Meliphagidae** [comment]
Checked today (21 April 2025) with latest version available in Google-Play-Store (Version 2025.4.4 from 14.04.2025), that there is no change yet visible. The bug still exists in portrait-mode and is not existing in landscape mode.

**Comment by nscharioth** [comment]
I am closing this as no longer planned.

If this issue should be prioritized, please reopen and assign milestone. @ungemeinfein @leagerndt
